#! /bin/sh

CXXFLAGS += -std=c++11

# If non standard installation directories 
#  for instance, uncomment and fix the following  

#PREFIX = ${HOME}/Soft
#CXXFLAGS += -I${PREFIX}/include
#LDFLAGS += -L${PREFIX}/lib

# Here with standard installation directories
#  otherwise modify the compilation variables

GMP_LIBS   += -lgmp
MPFR_LIBS +=  -lmpfr
FPLLL_LIBS += -lfplll

LOADLIBES +=  ${GMP_LIBS}  ${MPFR_LIBS} ${FPLLL_LIBS} 


.SUFFIXES: .o .c .cc  

.cc.o:
	g++  -o $@ -c $<   ${CXXFLAGS}
 
.cc:
	g++  -o $@ $<   ${CXXFLAGS}  ${LDFLAGS} ${LOADLIBES} 


 
